-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
from FIRST_HALF
INNER JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
where FIRST_HALF.TOTAL_ORDER > 3000 and ICECREAM_INFO.INGREDIENT_TYPE='fruit_based'

order by FIRST_HALF.TOTAL_ORDER desc

# SELECT HALF.FLAVOR
# FROM FIRST_HALF HALF
# INNER JOIN ICECREAM_INFO INFO
# ON HALF.FLAVOR = INFO.FLAVOR
# WHERE TOTAL_ORDER > 3000
# AND INGREDIENT_TYPE = 'fruit_based'
# ORDER BY TOTAL_ORDER DESC
